---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "api-city"
      version: "1.0.0"
      group: "gustavo.bueno"
    name: "api-city"
  spec:
    ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    selector:
      app: "api-city"
      version: "1.0.0"
      group: "gustavo.bueno"
    type: "ClusterIP"
- apiVersion: "image.openshift.io/v1"
  kind: "ImageStream"
  metadata:
    labels:
      app: "api-city"
      version: "1.0.0"
      group: "gustavo.bueno"
    name: "api-city"
- apiVersion: "image.openshift.io/v1"
  kind: "ImageStream"
  metadata:
    labels:
      app: "api-city"
      version: "1.0.0"
      group: "gustavo.bueno"
    name: "s2i-java"
  spec:
    dockerImageRepository: "fabric8/s2i-java"
- apiVersion: "build.openshift.io/v1"
  kind: "BuildConfig"
  metadata:
    labels:
      app: "api-city"
      version: "1.0.0"
      group: "gustavo.bueno"
    name: "api-city"
  spec:
    output:
      to:
        kind: "ImageStreamTag"
        name: "api-city:1.0.0"
    source:
      binary: {}
    strategy:
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          name: "s2i-java:2.3"
- apiVersion: "apps.openshift.io/v1"
  kind: "DeploymentConfig"
  metadata:
    labels:
      app: "api-city"
      version: "1.0.0"
      group: "gustavo.bueno"
    name: "api-city"
  spec:
    replicas: 2
    selector:
      app: "api-city"
      version: "1.0.0"
      group: "gustavo.bueno"
    template:
      metadata:
        labels:
          app: "api-city"
          version: "1.0.0"
          group: "gustavo.bueno"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          - name: "JAVA_APP_JAR"
            value: "/deployments/api-city-1.0.0.jar"
          - name: "JAVA_OPTS"
            value: "-Xms=128M -Xmx=256M -XX:+HeapDumpOnOutOfMemoryError"
          envFrom:
          - configMapRef:
              name: "api-city"
              optional: false
          image: ""
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
          name: "api-city"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - "api-city"
        from:
          kind: "ImageStreamTag"
          name: "api-city:1.0.0"
      type: "ImageChange"
- apiVersion: "route.openshift.io/v1"
  kind: "Route"
  metadata:
    labels:
      app: "api-city"
      version: "1.0.0"
      group: "gustavo.bueno"
    name: "api-city"
  spec:
    host: ""
    path: "/"
    port:
      targetPort: 8080
    to:
      kind: "Service"
      name: "api-city"
